name: Build docker image

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platform: linux/amd64,linux/arm64
          push: false
          tags: haohanyang/compass-web:${{ github.sha }}
