name: Build amd64 image

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build image
        run: docker build --platform linux/amd64 -t haohanyang/compass-web:${{ github.sha }} .
      - name: Run the compass web
        run: bash start-container.sh haohanyang/compass-web:${{ github.sha }}
