name: Build and publish compass web artifacts

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
        working-directory: ./compass
      - name: Bootstrap
        run: npm run bootstrap
        working-directory: ./compass
      - name: Build frontend
        run: npm run compile-sandbox --workspace=@mongodb-js/compass-web
        working-directory: ./compass
      - name: Bundle backend
        run: npm run bundle-sandbox-server --workspace=@mongodb-js/compass-web
        working-directory: ./compass
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compass-web-dist
          path: compass/packages/compass-web/dist
