name: Build linux/amd64 image

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t haohanyang/compass-web:${{ github.sha }} .
      - name: Run the compass web
        run: bash start-container.sh
