name: Build linux/amd64 image

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: false
          tags: haohanyang/compass-web:${{ github.sha }}
      - name: Run the compass web
        run: |
          timeout 30s docker run -it --rm haohanyang/compass-web:${{ github.sha }}

          if [ $? -eq 124 ]
          then
            echo "ok"
          else
            exit 1
          fi
