name: Create manifest on arm64 and amd64 images

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: haohanyang
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Create manifest
        run: |
          docker manifest create haohanyang/compass-web:${{ github.sha }} haohanyang/compass-web-amd64:${{ github.sha }} haohanyang/compass-web-arm64:${{ github.sha }}
          docker manifest create haohanyang/compass-web:latest haohanyang/compass-web-amd64:${{ github.sha }} haohanyang/compass-web-arm64:${{ github.sha }}
      - name: Push manifest
        run: |
          docker manifest push haohanyang/compass-web:${{ github.sha }}
          docker manifest push haohanyang/compass-web:latest
